---
- hosts: all
  become: true

  tasks:
    - name: Include task to install packages that enable apt over HTTPS
      ansible.builtin.include_tasks: includes/apt_over_https.yml

    - name: Include task to install useful packages
      ansible.builtin.include_tasks: includes/install_useful_packages.yml

    - name: Include task to generate CA certs
      ansible.builtin.include_tasks: includes/setup_ca.yml

    - name: Include task to Setup OpenVPN server
      ansible.builtin.include_tasks: includes/setup_server.yml

    - name: Include task to Manage users
      ansible.builtin.include_tasks: includes/user_management.yml

  handlers:
    - name: restart openvpn
      ansible.builtin.service:
        name: openvpn-server@server.service
        enabled: true
        state: restarted