---
- hosts: all
  become: true

  tasks:
    - name: Include task to install packages that enable apt over HTTPS
      ansible.builtin.include_tasks: includes/apt_over_https.yml

    - name: Include task to install useful packages
      ansible.builtin.include_tasks: includes/install_useful_packages.yml

    - name: Install OpenVPN
      ansible.builtin.apt:
        name: openvpn
        state: present
        update_cache: yes
      vars:
        packages:
          - openvpn

    - name: Include task to generate CA certs
      ansible.builtin.include_tasks: includes/setup_ca.yml

    - name: Setup OpenVPN server
      ansible.builtin.include_tasks: includes/setup_server.yml

  handlers:
    - name: restart openvpn
      service:
        name: openvpn-server@server.service
        enabled: true
        state: restarted